[0m[[0m[31merror[0m] [0m[0m/Users/sofieaasheim/scala-project/scala_project/tasks/task2_emme.scala:3:8: Task2 is already defined as object Task2[0m[0J
[0m[[0m[31merror[0m] [0m[0mobject Task2 extends App{[0m[0J
[0m[[0m[31merror[0m] [0m[0m       ^[0m[0J
[0m[[0m[31merror[0m] [0m[0mone error found[0m[0J
